### ISSUE TITLE
Can't specify keyEncoding as hex in a key stream

### ISSUE THREAD

**Issue by paulkernfeld** [dominictarr/level-sublevel#111]
Here's my minimal snippet to reproduce the issue. I'm not sure if this is the correct behavior or not, but it seems a little suspicious.
```javascript
var memdb = require('memdb')
var sublevel = require('level-sublevel')

var db = sublevel(memdb()).sublevel('subname')
db.createKeyStream({keyEncoding: 'hex'})
```

Here's the error that I get when I run the above:
```
buffer.js:594
        return this.hexWrite(string, offset, length);
                    ^

TypeError: Invalid hex string
    at TypeError (native)
    at Buffer.write (buffer.js:594:21)
    at fromString (buffer.js:113:26)
    at new Buffer (buffer.js:58:12)
    at Object.encodings.(anonymous function).encode (/Users/paul/projects/sublevel/node_modules/level-sublevel/node_modules/levelup/lib/encodings.js:60:42)
    at Object.encodeKey (/Users/paul/projects/sublevel/node_modules/level-sublevel/node_modules/levelup/lib/codec.js:28:37)
    at encodePrefix (/Users/paul/projects/sublevel/node_modules/level-sublevel/nut.js:31:44)
    at encodeKey (/Users/paul/projects/sublevel/node_modules/level-sublevel/nut.js:167:16)
    at Object.exports.toLtgt (/Users/paul/projects/sublevel/node_modules/level-sublevel/node_modules/ltgt/index.js:99:18)
    at Object.iterator (/Users/paul/projects/sublevel/node_modules/level-sublevel/nut.js:170:12)
```

**Comment by paulkernfeld** [comment]
BTW, if this not the intended behavior, I'd be happy to add a test for it and try to fix it.

**Comment by topfs2** [comment]
Not sure if related but I also noticed that if you do any sort of keyEncoding on the sublevel db it just dont' work either

```javascript
var db = sublevel(levelup('./mydb', {
	db: require('memdown')
}));

var sub = db.sublevel('SEQ', {
	keyEncoding: 'json'
})

db.pre(function (ch, add) {
  add({
    key: Date.now(), 
    value: ch.key, 
    type: 'put',
    // NOTE: pass the destination db to add the value to that subsection!
    prefix: sub
  })
})

db.put('key', 'VALUE', function (err) {
  // read all the records inserted by the hook!
  sub.createReadStream().on('data', console.log)
})
```

If you skip keyEncoding: 'json' it works.
Also if I set levelup options to keyEncoding: 'json' it works but that kindof defeats the purpose IMO :)

Modded from https://github.com/dominictarr/level-sublevel#hooks-example

**Comment by mablay** [comment]
With version 6.6.4 hex-encoding seems to work. 
Yet, for non buffer encodings the issue might remain.

```javascript
var memdb = require('memdb')
var sublevel = require('level-sublevel')

// array key encoding
var keyEncoding = {
  buffer: false,
  type: 'array',
  encode: arr => arr.join(':'),
  decode: str => str.split(':')
}

var db = sublevel(memdb()).sublevel('subname', {keyEncoding})
db.put(['foo', 'bar'], 'baz', () => {
  db.get(['foo', 'bar'], (err, value) => {
    if (err) throw err
    console.log(value)
    db.createKeyStream()
  })
})
```
Yields has an identical stack trace (after `at Object.encodeKey`) as stated by @paulkernfeld 

`db.createKeyStream()` would cause `encode` to be invoked 3 times as follows:

```
encode('\u0000')  // <Buffer 00>
encode('￿') // <Buffer ef bf bf>
encode(['foo', 'bar'])
```
The first invocation fails and causes the stack trace. I assume, the super level encoding method should have been called instead. But it's a wild guess.

My current workaround is to use a separate leveldb for custom key-encoding.
